cluster_name="mycluster"
qualifier_tag = "myqualifier"
use_secrets_manager = true
namespace_name = "mycluster.local"
dagster_rds_secret = "myclustersecret"
cluster_vpc_id = "vpc-012345"
cluster_subnet_ids = ["subnet-012345", "subnet-012346"]
db_security_group_id = "sg-012345"
region = "eu-central-1"
dagster_config_bucket = "my-dagster-config-bucket"
